### ISSUE TITLE
装了py2.7.8和pip7.1.2，蛋是运行不了

### ISSUE THREAD

**Issue by imbbctoo** [wangshunping/Starup-Game-Python#2]
$ python game.py start
Traceback (most recent call last):
  File "game.py", line 36, in <module>
    start()
  File "game.py", line 24, in start
    game.opening()
  File "D:\Quarantine Zone\game\Starup-Game-Python-master\core\startup_game.py", line 23, in opening
    print u'銆▒2015鍙堟槸涓€骞呭ソ鍏夋櫙鍟娿€▒'+u'锛屽姞鐝粨鏉熶箣鍚庣殑浣犵湅浜嗙湅鍥涘懆锛屽凡鏄繁澶溿€▒'
UnicodeEncodeError: 'ascii' codec can't encode character u'\u300e' in position 0: ordinal not in range(128)

**Comment by imbbctoo** [comment]
我错了。不该用git
