### ISSUE TITLE
bug 多啊

### ISSUE THREAD

**Issue by Gooooodman** [wangshunping/Starup-Game-Python#4]
第3周开始了，键盘的敲击声响起
PC哥一边上学一边写代码，项目进度推进了63
汪小小刚跑了8公里，精神状态良好，成功完成项目97

你可以解雇让你不爽的员工
(---按Y确认, 按其他键跳过---)

你有空余的工位, 你需要招募员工么
(---按Y确认, 按其他键跳过---)y
你可以最多可以雇佣3名员工，请谨慎选择:
## 当前雇佣程序员人数 2

是否结束雇佣，确认按 Y
(---按Y确认, 按其他键跳过---)h
Traceback (most recent call last):
  File "game.py", line 36, in <module>
    start()
  File "game.py", line 26, in start
    game.run()
  File "/data/game/core/startup_game.py", line 41, in run
    self.__mvp()
  File "/data/game/core/startup_game.py", line 48, in __mvp
    self.work_one_week()
  File "/data/game/core/startup_game.py", line 71, in work_one_week
    self.__hire_sys.hire_or_not()
  File "/data/game/core/hire_system.py", line 59, in hire_or_not
    self.hire()
  File "/data/game/core/hire_system.py", line 91, in hire
    self._hire()
  File "/data/game/core/hire_system.py", line 94, in _hire
    coder = self.avaliable_coders[randint(0, len(self.avaliable_coders)-1)]
  File "/usr/lib64/python2.6/random.py", line 228, in randint
    return self.randrange(a, b+1)
  File "/usr/lib64/python2.6/random.py", line 204, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)

**Comment by wangxiaoq** [comment]
这个bug我已经修复了，目前已提交PR，这个是我修复后的仓库地址：https://github.com/wangxiaoq/Starup-Game-Python

**Comment by Yudingding** [comment]
解雇之后没有把解雇人员放进avaliable_coders导致的，自己修改一下就可以
