### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by tuchang** [wangshunping/Starup-Game-Python#6]
```
bogon:starup-game-python username$ pip3 install -r requirments.txt
Collecting docopt==0.6.2 (from -r requirments.txt (line 1))
  Downloading docopt-0.6.2.tar.gz
Requirement already satisfied: termcolor==1.1.0 in /usr/local/lib/python3.6/site-packages (from -r requirments.txt (line 2))
Building wheels for collected packages: docopt
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /Users/username/Library/Caches/pip/wheels/b2/16/5f/c33a2bb5f2dce71205f8e65cbfd05647d79d441282be31fd82
Successfully built docopt
Installing collected packages: docopt
Successfully installed docopt-0.6.2
bogon:starup-game-python username$ python game.py start
Traceback (most recent call last):
  File "game.py", line 17, in <module>
    from docopt import docopt
ImportError: No module named docopt


```

**Comment by tuchang** [comment]
```
bogon:starup-game-python username$ pip3 install docopt
Requirement already satisfied: docopt in /usr/local/lib/python3.6/site-packages
bogon:starup-game-python tuchang$ python3 game.py start
Traceback (most recent call last):
  File "game.py", line 17, in <module>
    from docopt import docopt
ImportError: No module named 'docopt'
```

**Comment by SymphonyPy** [comment]
不是写了只支持python2么？

**Comment by tuchang** [comment]
稍微改改括号啊什么的 好像也能进去

**Comment by SymphonyPy** [comment]
没试 我以为有些库不支持3

**Comment by jeffsui** [comment]
怎么乱码了兄弟？
